### ISSUE TITLE
Mark as read button stops working in oldest-first

### ISSUE THREAD

**Issue by tanriol** [tanriol/digest#17]
See also https://www.mozdev.org/bugs/show_bug.cgi?id=24757 and #10

**Comment by ghost** [comment]
I found another trace of this bug (similar to the 24757 bug) in http://github.com/Tanriol/digest/blob/master/chrome/content/feedview.js#L168-169, this.selectedEntry appears as undefined. In the bug it says "30 minutes to an hour", I could reduce it to every time the feeds are updated (also manually).
EDIT: Not only fails with "mark as read" but also with "move to trash".

**Comment by tanriol** [comment]
Thanks for reporting. I've managed to reproduce the bug, so it should be fixed soon.
