### ISSUE TITLE
Error on single feed notification

### ISSUE THREAD

**Issue by a-little-help** [tanriol/digest#60]
In the notification where only one feed is updated there is an error: the feed name isn't correct because the name the addon get is the first on the list of feed.
e.g.
I've a feeds list of 5 item,
A ,B, C, D, E
if only C is updated (3 new item) the notification get the name of feed A displaying
3 new items in "A"
where it should be 
3 new items in "C"

from the file brief.properties
LOCALIZATION NOTE e.g. "5 new items in "Feed name""
updateAlertText.singleFeed=#numItems new %1$S in "%2$S"
The sintax is correct.....
thanks!
a-little-help

**Comment by tanriol** [comment]
Should be fixed by c5062cf059bdb883bc1867547d4e0ca79d4b6e12, thanks.
