### ISSUE TITLE
Digest 1.0.4 misbehaving when the browser hasn't be closed for a long time.

### ISSUE THREAD

**Issue by hurda** [tanriol/digest#62]
I started to notice that Digest is mishaving when the browser hasn't been cycled for a very long time, i.e. two to three days of uptime.

Problems like the scheduled feed-update stopping randomly with the progressbar remaining in view, clicking on feed-items in "view headlines"/"unread"-view doesn't remove them, or the unread-number and the itemlist not changing when hitting the "n" key to mark items in view as read until I close the Digest-tab and reopen it.

And the following error is being shown in the console upon several operations within Digest:

```
Error: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIDOMJSWindow.setTimeout]
Source file: chrome://digest/content/brief-overlay.js
Line: 214
```

**Comment by hurda** [comment]
The error seems to be unrelated to Digest as I've now got it for other extensions and scripts, too.

**Comment by tanriol** [comment]
This error seems to be related to Digest. At least it happens in the Digest's javascript.

@hurda, what OS and Firefox version do you use?

**Comment by hurda** [comment]
Vista, Firefox 22.

**Comment by tanriol** [comment]
@hurda, 32-bit or 64-bit?

**Comment by hurda** [comment]
Sorry, 32bit. With the /3GB switch enabled, if that has any relevance.

**Comment by tanriol** [comment]
It seems that this error is not Digest-specific and happens sometimes in different projects, but no known explanation exists. If I understand you correctly, your Firefox starts misbehaving on setTimeout after several days of uptime. I'd suggest filing a FIrefox bug about this.

Closing this bug as INVALID. If you file a Firefox bug, please post a link here.

**Comment by hurda** [comment]
Will do.
