### ISSUE TITLE
Images do not appear

### ISSUE THREAD

**Issue by MDnnrd** [tanriol/digest#64]
v1.0.4 - images/videos do not appear in reading layout, only headers and the placeholders where the images should be shown are visible.

**Comment by tanriol** [comment]
It works for me. Could you verify that:
- the images are not included with relative URLs (does not work, #9);
- no other addon blocks them from loading (something like RequestPolicy may do this)

**Comment by MDnnrd** [comment]
It must have been the version of Request Policy (.5  stable release) because when I updated to the beta 1.x version, the images appear.  I will spot check a few other things if issues continue.  Thank you for your quick response.

Michael
