### ISSUE TITLE
Translated english to italian description and information on add on's web page

### ISSUE THREAD

**Issue by a-little-help** [tanriol/digest#65]
hi, i've translated the description and the information about digest that are on its web page. Following there are the original english text and the italian translation. I don't now if there is the possibility of offering a translated text to the italian user of the page. :)

DESCRIPTION
ENGLISH
//////
A simple yet powerful feed reader integrated with Live Bookmarks.
Reading RSS feeds is easy and intuitive. Starring and tagging is fully integrated with Firefox bookmarks - in a single click. 
Offline feed storage and full-text search included.
//////
ITALIAN
//////
Un semplice ma potente aggregatore di feed integrato con i Segnalibri Live.
Leggere i feed RSS è semplice ed intuitivo. Il contrassegno ed il tag degli elementi sono completamente integrati con i segnalibri di Firefox - con un solo click.
I feed sono consultabili anche offline ed è disponibile la ricerca completa degli elementi.
//////
\DESCRIPTION

INFORMATION
ENGLISH
//////
Digest is a fork of the Brief feed reader aiming to update it for the modern Firefox versions, fix the bugs still present and develop it furtherer without losing clarity and simplicity.

Digest is trying to make working with feeds elegant and smooth. No excess substances unless absolutely required.
No need to check for new posts - the essence of a feed reader is that it watches and tells you the results.
No separate accounts and registrations - Firefox Sync is ready to transfer the posts You starred or tagged to any other device You use Firefox on.
No need for Internet to re-read a post - Digest keeps them on Your computer for the amount of time You tell it to.
No need to google if you know what you need - full-text search is built into Digest itself.
No privacy leak - Digest does not tell anyone which feeds do You read.
//////
ITALIAN
//////
Digest è un'evoluzione dell'aggregatore di feed Brief che cerca di aggiornarlo per le versioni moderne di Firefox, di correggerne i bug ancora presenti e di svilupparne nuove ulteriori caratteristiche senza però perdere la chiarezza e la semplicità che lo contraddistinguono.

Digest cerca di rendere il lavorare con i feed facile ed elegante. Niente di più oltre a quanto richiesto.
Non c'è bisogno di controllare la presenza di nuovi post - l'essenza di un aggregatore è che lui osserva e poi ti fornisce il risultato che tu vuoi.
Non c'è bisogno di account o registrazioni - Firefox Sync è quanto basta per trasferire i feed che tu contrassegni o tagghi in ogni altro dispositivo sul quale usi Firefox.
Non c'è bisogno di connessione internet per rileggere i post già scaricati - Digest li conserva sul tuo computer per il tempo (o numero) che vuoi tu.
Non c'è bisogno di google se già sai cosa cercare - la ricerca completa degli elementi è parte integrante di Digest.
Non ci sono problemi di privacy - Digest non dirà a nessuno quali feed stai seguendo.
//////
\INFORMATION

![webpage](https://f.cloud.github.com/assets/4947428/761036/9b4e2d02-e7c0-11e2-8a48-9e9045118d2d.JPG)

a-little-help

**Comment by tanriol** [comment]
Thank you. Unfortunately, the description has a length limit of approximately 250 characters, which is exceeded by your translation. Is it possible to shorten the description?

**Comment by a-little-help** [comment]
Ops, i don't know that.... here is a shorter but complete description (250 characters, the italian)
DESCRIPTION
ENGLISH
//////
A simple yet powerful feed reader integrated with Live Bookmarks.
Reading RSS feeds is easy and intuitive. Starring and tagging is fully integrated with Firefox bookmarks - in a single click.
Offline feed storage and full-text search included.
//////
ITALIAN
//////
Un semplice ma potente aggregatore di feed integrato con i Segnalibri Live.
Leggere i feed RSS è semplice ed intuitivo. I contrassegni ed i tag sono integrati con i segnalibri di Firefox.
Salvataggio dei feed offline e ricerca degli elementi inclusi.
//////
\DESCRIPTION

a-little-help

**Comment by tanriol** [comment]
AMO seems to count characters slightly incorrectly.
"Ensure this value has at most 250 characters (it has 252)."

**Comment by a-little-help** [comment]
now i hope/think it's ok..... ;)

ITALIAN
//////
Un semplice ma potente aggregatore di feed integrato con i Segnalibri Live.
Leggere i feed RSS è semplice ed intuitivo. Contrassegni e tag sono integrati con i segnalibri di Firefox.
Salvataggio dei feed offline e ricerca degli elementi inclusi.
//////

a-little-help

**Comment by tanriol** [comment]
Thanks, applied.
