### ISSUE TITLE
A patch for fixing relative url in rss.xml

### ISSUE THREAD

**Issue by kid23** [tanriol/digest#70]
Hey, Tanriol. I did some research on the relative url, and wrote a patch for fixing it. May be it's not a good solution, but it works.
First, when we got the feed responseText, check if it has relative url in the xml. If has, add base url to all relative urls. The base url is extracted from feed url.

diff --git a/modules/FeedUpdateService.jsm b/modules/FeedUpdateService.jsm
index c3d5c35..fd9d23b 100644
--- a/modules/FeedUpdateService.jsm
+++ b/modules/FeedUpdateService.jsm
@@ -411,7 +411,14 @@ FeedFetcher.prototype = {
             self.timeoutTimer.cancel();
             try {
                 let uri = Services.io.newURI(self.feed.feedURL, null, null);
-                self.parser.parseFromString(self.request.responseText, uri);
-       let text = self.request.responseText;
-       if (self.request.responseText.search("<a href='/") != -1) {
-           let base = self.feed.feedURL.substring(0, self.feed.feedURL.indexOf("/", 8)+1);
-           let t = text.replace("<a href='/","<a href='" + base,"gi");
-           text = t.replace("<link><![CDATA[/","<link><![CDATA[" + base,"gi");
-           Cu.reportError('Add base url ' + base);
-       }
-                self.parser.parseFromString(text, uri);
           }
           catch (ex) {
               self.finish('error');

![12](https://f.cloud.github.com/assets/4679823/789096/b6c58390-eb09-11e2-879e-4147db25150c.png)

**Comment by tanriol** [comment]
@kid23, a nice try. However, it does not work with any of

``` html
<a href="/something">link</a>
<a target='blank' href='something'>link</a>
<a  href='/something'>link</a>
<a href='index.html'>link</a>
<img src='/image.png'/>
```

Any problem may be solved with regular expressions. However, for lots of problems they are a wrong tool. This is one of them.

I am not going to use search-and-replace, regular expressions or some hand-crafted parser for modifying the feed items in-place. This problem requires another kind of solution. It may be parsing the feed with Firefox and modifying all URIs, or wrapping it in an item that modifies the base URI for us, but not parsing HTML ourselves.
