### ISSUE TITLE
Problem installing in FF15

### ISSUE THREAD

**Issue by balthamossa2b** [tanriol/digest#73]
Sorry if doesn't belong here as I'm pretty much a newbie with both Github and Firefox addons... how do I install it?

I tried renaming the zip to xpi but it doesn't work, FF says "The addon seems to be corrupt".

I really want to try this branch of Brief but I have no idea on how to use it. Any help will be appreciated.

**Comment by tanriol** [comment]
Most easily installed from https://addons.mozilla.org/en-US/firefox/addon/digest/ with the button "Add to Firefox"
