### ISSUE TITLE
OK button has no effect on custom CSS window

### ISSUE THREAD

**Issue by Artfunkel** [tanriol/digest#74]
The OK button on the "Edit Custom Style" window (Options > Customize)  can be clicked, but does not close the window. This makes it is impossible to save custom CSS. The Cancel button works correctly.
- Digest 1.0.4
- Firefox 22
- Win7 x64

**Comment by tanriol** [comment]
It works for me on 1.0.4/Nightly/Linux x64. Unfortunately I have no Win7 x64 to test this right now.
Could you please open the Error Console with Ctrl+Shift+J, try to customize CSS and save it and look for possibly related errors? By the way, does the error appear in a clean Firefox profile?

**Comment by Artfunkel** [comment]
There are no console messages.

The bug does not occur with a new profile. When I opened the window in the new profile I noticed that there was already some text in the CSS edit box, whereas in my normal profile there is nothing.

**Comment by tanriol** [comment]
It seems like you're not allowed to create a new file in the "chrome" subfolder of your profile folder for some reason. Does a file <firefox profile folder>\chrome\brief-custom-style.css exist? Can you modify its contents if it exists or create it if it does not?

**Comment by Artfunkel** [comment]
It existed but had somehow become read-only. With that flag removed everything is now working correctly again.

Unfortunately a two layers of modal windows makes CSS editing painful...it would be better to just open the file with the system text editor IMO.

**Comment by tanriol** [comment]
OK, so I'm closing this bug as everything works. The reason for bad permissions may be in a previously fixed bug.
I'll look into using a better editor.

Thank you very much for reporting.
