### ISSUE TITLE
New subscription without link clicking

### ISSUE THREAD

**Issue by ghost** [tanriol/digest#82]
Hi.  This is not really a bug report, just a request for help.  Sorry for that, couldn't find a way to contact you.

The problem is: some blog pages have no visible link to click to subscribe to them, but they have a 

 <link rel="alternate" type="application/rss+xml"> 

tag in their head.  You can view the page source and copy the feed URL from there, but how to tell Digest about it without going through the Firefox subscription UI?  Simply creating a new bookmark or folder under the Digest folder doesn't seem to work.

**Comment by tanriol** [comment]
Simply creating is not enough. The Firefox subscription UI is the only method of creating a Live Bookmark in stock Firefox I know. Some other addon may be able to streamline this part, but Brief does not provide UI for this now.
